spring.application.name=tryal

# postgresql
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/h2ak_db}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# jpa/hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# spring security
spring.security.user.name=${ADMIN_USERNAME:burrito}
spring.security.user.password=${ADMIN_USERNAME:boys}

# environment
spring.application.environment=${ENV:dev}

# redis
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=${REDIS_PASSWORD:password}
spring.redis.database=0