spring.application.name=h2ak

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/h2ak_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Spring Security
spring.security.user.name=burrito
spring.security.user.password=boys

# Environment
spring.application.environment=${ENV:dev}